[book]
authors = ["MarkBruns"]
language = "en"
multilingual = false
src = "src"
title = "Relationship-Based Marketing With Accelerated Negotiation AND Follow-Through Becomes Reputation-Based Marketing"
